######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 25 10:46:47 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += album.hh browser.hh math.hh pictureflow.h
SOURCES += album.cc browser.cc main.cc pictureflow.cpp

QMAKESPEC = macx-g++
