# $Id$
######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 25 10:46:47 2009
######################################################################

TEMPLATE = app
TARGET = ps
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += album.hh browser.hh math.hh 
SOURCES += album.cc browser.cc main.cc 

