# $Id$
######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 25 10:46:47 2009
######################################################################

CONFIG += warn_on
TEMPLATE = app
TARGET = ps
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += album.hh render.hh fpmath.hh logger.hh
SOURCES += album.cc render.cc main.cc logger.cc

